<Project Sdk="Microsoft.NET.Sdk">
    <!-- Import tModLoader mod properties -->
    <Import Project="..\tModLoader.targets" />

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <BuildMod>false</BuildMod>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <!-- Roslynator Analyzers -->
      <PackageReference Include="Roslynator.Analyzers" Version="4.15.0">
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        <PrivateAssets>all</PrivateAssets>
      </PackageReference>

      <!-- ValkyrieLib -->
      <ProjectReference Include="..\ValkyrieLib\ValkyrieLib.csproj" />

      <!-- DragonLens -->
      <Reference Include="DragonLens">
        <HintPath>ModAssemblies\DragonLens.dll</HintPath>
      </Reference>

      <!-- Exclude Source -->
      <Compile Remove="Source\**\*.cs" />
    </ItemGroup>
</Project>
